# Generated by Django 6.1 on 2026-08-13 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='reminder',
            field=models.CharField(choices=[('none', 'No reminder'), ('1_hour', '1 hour before'), ('1_day', '1 day before'), ('2_days', '2 days before'), ('3_days', '3 days before')], default='1_hour', max_length=10),
        ),
    ]
