# Generated by Django 6.1.1 on 2026-09-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignment_due_time_assignment_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=6),
        ),
    ]
