# Generated by Django 6.1.1 on 2026-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assignment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
